### ISSUE TITLE
Multi-threads support

### ISSUE THREAD

**Issue by wusyong** [wusyong/smol-potat#1]
What we do now is a single thread executor. Will be great if we can provide other options like multi thread based on users choice or cpu core.

**Comment by Restioson** [comment]
Could default to the number of logical cores

**Comment by wusyong** [comment]
After trying a bit, I think it should just let users decide how many threads should create. Otherwise, it ends up requiring users to add another dependency(eg. `num_cpu`).

I have added multithread support, so I'm going to close this for now. But feel free to open another one or PR if you think it is still a good option.

**Comment by Restioson** [comment]
Maybe it could be a `feature`?

**Comment by meh** [comment]
Yeah, I'd like to have it as a feature, would use.

**Comment by danieleades** [comment]
the current implementation seems to *prevent* a user from using `num_cpus` to set the number of threads. The proc macro accepts only a literal number. if this accepted a function, you could write

```rust
#[smol_potat::main(threads=num_cpus::get().max(1))]
async fn main() {
    println!("Hello, World!")
}
```
(but it would be tidier to have a special case for this)

**Comment by danieleades** [comment]
see #4
